import { ADMIN_STYLE } from './admin-style.js';

export const ADMIN_HTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EPhone 反馈管理</title>
<style>${ADMIN_STYLE}</style></head><body><header>EPhone · 反馈管理 <button id="logout" hidden>退出</button></header><div id="login"><h2>管理员登录</h2><p class="meta">输入只保存在本次浏览器标签页中的管理密钥。</p><form id="login-form"><label>管理密钥<input name="token" type="password" autocomplete="off" pattern="[0-9a-fA-F]{64}" required></label><button class="primary">进入管理页</button></form><div id="login-notice" role="status"></div></div><main hidden><aside><nav><button data-kind="all" class="active">全部</button><button data-kind="private">匿名对话</button><button data-kind="public">公开反馈</button><button id="refresh">刷新</button></nav><div class="toolbar"><input id="search" placeholder="搜索标题或编号" aria-label="搜索反馈"><select id="filter" aria-label="状态筛选"><option value="all">全部状态</option><option value="needs_reply">待回复</option><option value="pending">待审核</option><option value="visible">已公开</option><option value="closed">已关闭</option></select></div><div id="notice" role="status"></div><div id="list" class="list">正在加载…</div><button id="more" hidden>加载更早反馈</button></aside><section id="detail"><p class="meta">选择一条反馈查看并回复。</p></section></main>
<script>
(function(){
var all=[],kind='all',selected=null,nextCursor=null,token='';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function date(v){return new Date(v).toLocaleString('zh-CN')}
function label(v){return ({wish:'许愿',feedback:'反馈',bug:'报错',other:'其他',pending:'待审核',visible:'已公开',hidden:'已隐藏',open:'进行中',closed:'已关闭'})[v]||v}
function notice(v){document.getElementById('notice').textContent=v||''}
function lock(){token='';sessionStorage.removeItem('ephone_feedback_admin_token');document.getElementById('login').hidden=false;document.querySelector('main').hidden=true;document.getElementById('logout').hidden=true}
async function api(path,options){var opts=Object.assign({cache:'no-store'},options||{});var headers=new Headers(opts.headers||{});headers.set('Authorization','Bearer '+token);opts.headers=headers;var r=await fetch('/api'+path,opts);var data=await r.json().catch(function(){return {}});if(r.status===401)lock();if(!r.ok)throw Error(data.error||'请求失败');return data}
async function signIn(value){token=value.trim().toLowerCase();await api('/session');sessionStorage.setItem('ephone_feedback_admin_token',token);document.getElementById('login').hidden=true;document.querySelector('main').hidden=false;document.getElementById('logout').hidden=false;document.getElementById('login-notice').textContent='';await reload()}
function list(){var el=document.getElementById('list');var filter=document.getElementById('filter').value;var query=document.getElementById('search').value.trim().toLowerCase();var rows=all.filter(function(t){return (kind==='all'||t.kind===kind)&&(filter==='all'||(filter==='needs_reply'?!t.visitor_closed&&t.last_visitor_at>t.last_admin_at:t.status===filter))&&(!query||t.title.toLowerCase().includes(query)||t.id.includes(query))});el.innerHTML=rows.length?rows.map(function(t){return '<button data-id="'+t.id+'" class="'+(selected===t.id?'selected':'')+'"><b>'+(!t.visitor_closed&&t.last_visitor_at>t.last_admin_at?'● ':'')+esc(t.title)+'</b><small>'+(t.kind==='private'?'匿名':'公开')+' · '+esc(label(t.category))+' · '+esc(label(t.status))+(t.visitor_closed?' · 用户已结束往来':'')+' · '+date(t.updated_at)+'</small></button>'}).join(''):'暂无匹配反馈';document.getElementById('more').hidden=!nextCursor}
async function loadPage(reset){try{notice('');var data=await api('/threads'+(!reset&&nextCursor?'?before='+encodeURIComponent(nextCursor):''));all=reset?data.threads:all.concat(data.threads);nextCursor=data.nextCursor;list();if(reset&&selected&&all.some(function(t){return t.id===selected}))await detail(selected)}catch(e){notice(e.message)}}
async function reload(){return loadPage(true)}
async function detail(id){try{selected=id;list();var data=await api('/threads/'+id);var t=data.thread;var options=t.kind==='public'?['pending','visible','hidden','closed']:['open','closed'];var el=document.getElementById('detail');el.innerHTML='<h2>'+esc(t.title)+'</h2><div class="meta">'+(t.kind==='private'?'匿名对话':'公开反馈')+' · '+esc(label(t.category))+(t.visitor_closed?' · 用户已结束往来':'')+' · '+esc(t.nickname||'匿名用户')+' · '+date(t.created_at)+'</div><div class="toolbar"><label>状态 <select id="thread-status">'+options.map(function(v){return '<option value="'+v+'" '+(v===t.status?'selected':'')+'>'+label(v)+'</option>'}).join('')+'</select></label><button id="save-status">保存状态</button><button id="delete-thread" class="danger">删除整段对话</button></div><details class="note"><summary>内部备注</summary><label>内部备注<textarea id="thread-note" maxlength="1000"></textarea></label><button id="save-note">保存备注</button></details><div id="messages">'+data.messages.map(function(m){return '<article class="message '+(m.sender==='admin'?'admin':'visitor')+'"><small>'+(m.sender==='admin'?'我':'用户')+' · '+date(m.created_at)+'</small>'+esc(m.body)+(m.attachment_key?'<button data-image="'+m.attachment_key+'">查看截图</button>':'')+'</article>'}).join('')+'</div>'+(t.visitor_closed?'<p class="meta">投信者已结束往来，无法继续回信。</p>':'<form id="reply" class="reply"><label>回复<textarea name="body" maxlength="5000" required></textarea></label><button class="primary">发送回复</button></form>');
document.querySelector('main').classList.add('thread-open');
el.insertAdjacentHTML('afterbegin','<button type="button" class="mobile-back" id="back-list">‹ 返回收件箱</button>');
el.querySelector('#back-list').onclick=function(){document.querySelector('main').classList.remove('thread-open')};
el.querySelector('#thread-note').value=t.note||'';
el.querySelector('#messages').scrollTop=el.querySelector('#messages').scrollHeight;
el.querySelector('#save-status').onclick=async function(){try{await api('/threads/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:el.querySelector('#thread-status').value})});await reload()}catch(e){notice(e.message)}};
el.querySelector('#save-note').onclick=async function(){try{await api('/threads/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:el.querySelector('#thread-note').value})});notice('备注已保存')}catch(e){notice(e.message)}};
el.querySelector('#delete-thread').onclick=async function(){if(!confirm('确定永久删除这段对话及截图吗？'))return;try{await api('/threads/'+id,{method:'DELETE'});selected=null;document.querySelector('main').classList.remove('thread-open');el.innerHTML='<p>已删除。</p>';await reload()}catch(e){notice(e.message)}};
if(el.querySelector('#reply'))el.querySelector('#reply').onsubmit=async function(ev){ev.preventDefault();var body=el.querySelector('[name=body]').value.trim();if(!body)return;try{await api('/threads/'+id+'/reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:body})});await reload()}catch(e){notice(e.message)}};
el.querySelectorAll('[data-image]').forEach(function(button){button.onclick=async function(){try{var r=await fetch('/api/attachments/'+button.dataset.image,{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error('截图加载失败');var url=URL.createObjectURL(await r.blob());var img=new Image();img.src=url;img.alt='反馈截图';img.onload=function(){URL.revokeObjectURL(url)};button.replaceWith(img)}catch(e){notice(e.message)}}});
}catch(e){notice(e.message)}}
document.getElementById('list').onclick=function(ev){var b=ev.target.closest('[data-id]');if(b)detail(b.dataset.id)};
document.querySelectorAll('[data-kind]').forEach(function(b){b.onclick=function(){kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(function(x){x.classList.toggle('active',x===b)});list()}});
document.getElementById('refresh').onclick=reload;document.getElementById('more').onclick=function(){loadPage(false)};document.getElementById('search').oninput=list;document.getElementById('filter').onchange=list;
document.getElementById('login-form').onsubmit=async function(ev){ev.preventDefault();try{await signIn(ev.target.elements.token.value)}catch(e){document.getElementById('login-notice').textContent=e.message}};
document.getElementById('logout').onclick=lock;
var saved=sessionStorage.getItem('ephone_feedback_admin_token');if(saved)signIn(saved).catch(function(e){document.getElementById('login-notice').textContent=e.message});
})();
</script></body></html>`;
